# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(787, 498)
        Dialog.setAutoFillBackground(True)
        self.camera = QtWidgets.QLabel(Dialog)
        self.camera.setGeometry(QtCore.QRect(20, 90, 341, 331))
        self.camera.setAutoFillBackground(False)
        self.camera.setStyleSheet("#camera{\n"
" background-color: lightgray;\n"
"}")
        self.camera.setText("")
        self.camera.setObjectName("camera")
        self.test = QtWidgets.QPushButton(Dialog)
        self.test.setGeometry(QtCore.QRect(90, 450, 211, 41))
        self.test.setStyleSheet("#test{\n"
"background: green;\n"
"font-size:20px;\n"
"}")
        self.test.setObjectName("test")
        self.captured = QtWidgets.QLabel(Dialog)
        self.captured.setGeometry(QtCore.QRect(410, 90, 341, 331))
        self.captured.setAutoFillBackground(False)
        self.captured.setStyleSheet("#captured{\n"
" background-color: lightgray;\n"
"}")
        self.captured.setText("")
        self.captured.setObjectName("captured")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(420, 430, 131, 16))
        self.label.setObjectName("label")
        self.prediction_result = QtWidgets.QLabel(Dialog)
        self.prediction_result.setGeometry(QtCore.QRect(420, 450, 331, 41))
        self.prediction_result.setStyleSheet("#prediction_result{\n"
"background:yellow;\n"
"font-size:15px}")
        self.prediction_result.setText("")
        self.prediction_result.setObjectName("prediction_result")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(150, 50, 81, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(530, 50, 121, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.test.setText(_translate("Dialog", "Test"))
        self.label.setText(_translate("Dialog", "Prediciton result bellow"))
        self.label_2.setText(_translate("Dialog", "WebCam"))
        self.label_3.setText(_translate("Dialog", "Image To Be Predicted "))
